UPDATE translations SET `value`="Lista de alunos" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="pt_BR";
UPDATE translations SET `value`="List of users" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="en";
UPDATE translations SET `value`="List of users" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="en_US";
UPDATE translations SET `value`="List of users" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="en_GB";
UPDATE translations SET `value`="List of users" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="en_IE";
UPDATE translations SET `value`="Listado de usuarios" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="es";
UPDATE translations SET `value`="Listado de usuarios" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="es_AR";
UPDATE translations SET `value`="Listado de usuarios" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="es_CL";
UPDATE translations SET `value`="Lista de usuarios" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="es_MX";
UPDATE translations SET `value`="Listado de usuarios" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="es_ES";
UPDATE translations SET `value`="Liste der Nutzer" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="de";
UPDATE translations SET `value`="Liste des utilisateurs" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="fr";
UPDATE translations SET `value`="Lista utenti" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="it";
UPDATE translations SET `value`="Lijst van gebruikers" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="nl";
UPDATE translations SET `value`="Lista de utilizadores" WHERE `key`="gym_partner_web.partner_data.users_list.title" and `locale`="pt_PT";
UPDATE translations SET `value`="Usuários do Gympass que visitaram a sua academia." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="pt_BR";
UPDATE translations SET `value`="Gympass users that visited your gym." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="en";
UPDATE translations SET `value`="Gympass users who have visited your gym." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="en_US";
UPDATE translations SET `value`="Gympass users that have visited your gym." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="en_GB";
UPDATE translations SET `value`="Gympass users that have visited your gym." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="en_IE";
UPDATE translations SET `value`="Usuarios Gympass que han visitado tu gimnasio." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="es";
UPDATE translations SET `value`="Usuarios de Gympass que visitaron tu gimnasio." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="es_AR";
UPDATE translations SET `value`="Usuarios de Gympass que han visitado tu gimnasio." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="es_CL";
UPDATE translations SET `value`="Usuarios de Gympass que han visitado tu gimnasio." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="es_MX";
UPDATE translations SET `value`="Usuarios Gympass que han visitado tu gimnasio." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="es_ES";
UPDATE translations SET `value`="Gympass-Nutzer, die Ihr Fitnessstudio besucht haben." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="de";
UPDATE translations SET `value`="Clients Gympass qui se sont rendus dans votre salle." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="fr";
UPDATE translations SET `value`="Utenti Gympass che hanno visitato la tua struttura." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="it";
UPDATE translations SET `value`="Gympass gebruikers welke je locatie hebben bezocht." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="nl";
UPDATE translations SET `value`="Utilizadores Gympass que visitaram o seu ginásio." WHERE `key`="gym_partner_web.partner_data.users_list.tooltip" and `locale`="pt_PT";
UPDATE translations SET `value`="Primeira visita" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="pt_BR";
UPDATE translations SET `value`="First visit" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="en";
UPDATE translations SET `value`="First visit" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="en_US";
UPDATE translations SET `value`="First visit" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="en_GB";
UPDATE translations SET `value`="First visit" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="en_IE";
UPDATE translations SET `value`="Primera visita" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="es";
UPDATE translations SET `value`="Primera visita" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="es_AR";
UPDATE translations SET `value`="Primera visita" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="es_CL";
UPDATE translations SET `value`="Primera visita" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="es_MX";
UPDATE translations SET `value`="Primera visita" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="es_ES";
UPDATE translations SET `value`="Erster Besuch" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="de";
UPDATE translations SET `value`="Première visite" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="fr";
UPDATE translations SET `value`="Prima visita" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="it";
UPDATE translations SET `value`="Eerste bezoek" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="nl";
UPDATE translations SET `value`="Primeira visita" WHERE `key`="gym_partner_web.partner_data.users_list.first_visit" and `locale`="pt_PT";
UPDATE translations SET `value`="Última visita" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="pt_BR";
UPDATE translations SET `value`="Last visit" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="en";
UPDATE translations SET `value`="Last visit" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="en_US";
UPDATE translations SET `value`="Last visit" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="en_GB";
UPDATE translations SET `value`="Last visit" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="en_IE";
UPDATE translations SET `value`="Última visita" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="es";
UPDATE translations SET `value`="Última visita" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="es_AR";
UPDATE translations SET `value`="Última visita" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="es_CL";
UPDATE translations SET `value`="Última visita" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="es_MX";
UPDATE translations SET `value`="Última visita" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="es_ES";
UPDATE translations SET `value`="Letzter Besuch" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="de";
UPDATE translations SET `value`="Dernière visite" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="fr";
UPDATE translations SET `value`="Ultima visita" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="it";
UPDATE translations SET `value`="Laatste bezoek" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="nl";
UPDATE translations SET `value`="Última visita" WHERE `key`="gym_partner_web.partner_data.users_list.last_visit" and `locale`="pt_PT";
UPDATE translations SET `value`="Receita mensal acumulada" WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="pt_BR";
UPDATE translations SET `value`="Monthly revenue amount" WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="en";
UPDATE translations SET `value`="Revenue per month" WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="en_US";
UPDATE translations SET `value`="Monthly revenue " WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="en_GB";
UPDATE translations SET `value`="Monthly revenue " WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="en_IE";
UPDATE translations SET `value`="Ingresos totales por mes" WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="es";
UPDATE translations SET `value`="Ingresos totales por mes" WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="es_AR";
UPDATE translations SET `value`="Ingresos totales por mes" WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="es_CL";
UPDATE translations SET `value`="Ingresos totales por mes" WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="es_MX";
UPDATE translations SET `value`="Ingresos totales por mes" WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="es_ES";
UPDATE translations SET `value`="Monatlicher Umsatzbetrag" WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="de";
UPDATE translations SET `value`="Montant des revenus mensuels" WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="fr";
UPDATE translations SET `value`="Ricavi per mese" WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="it";
UPDATE translations SET `value`="Opbrengst per maand" WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="nl";
UPDATE translations SET `value`="Rendimento total mensal" WHERE `key`="gym_partner_web.partner_data.amount_per_month" and `locale`="pt_PT";
UPDATE translations SET `value`="Total de check-ins por mês" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="pt_BR";
UPDATE translations SET `value`="Total of check-ins per month" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="en";
UPDATE translations SET `value`="Total check-ins per month" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="en_US";
UPDATE translations SET `value`="Monthly validations" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="en_GB";
UPDATE translations SET `value`="Monthly validations" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="en_IE";
UPDATE translations SET `value`="Check-ins totales por mes" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="es";
UPDATE translations SET `value`="Check-ins totales por mes" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="es_AR";
UPDATE translations SET `value`="Check-ins totales por mes" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="es_CL";
UPDATE translations SET `value`="Check-ins totales por mes" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="es_MX";
UPDATE translations SET `value`="Check-ins totales por mes" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="es_ES";
UPDATE translations SET `value`="Summe der Check-Ins pro Monat" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="de";
UPDATE translations SET `value`="Total des check-in par mois" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="fr";
UPDATE translations SET `value`="Check-in totali per mese" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="it";
UPDATE translations SET `value`="Totaal aantal check-ins per maand" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="nl";
UPDATE translations SET `value`="Check-ins totais por mês" WHERE `key`="gym_partner_web.partner_data.checkins_per_month" and `locale`="pt_PT";
UPDATE translations SET `value`="Check-ins por período do dia" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="pt_BR";
UPDATE translations SET `value`="Check-ins heatmap" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="en";
UPDATE translations SET `value`="Check-ins by time of day" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="en_US";
UPDATE translations SET `value`="Validations by time of day" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="en_GB";
UPDATE translations SET `value`="Validations by time of day" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="en_IE";
UPDATE translations SET `value`="Gráfico de los check-ins" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="es";
UPDATE translations SET `value`="Gráfico de los check-ins" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="es_AR";
UPDATE translations SET `value`="Gráfico de los check-ins" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="es_CL";
UPDATE translations SET `value`="Gráfico de los check-ins" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="es_MX";
UPDATE translations SET `value`="Gráfico de los check-ins" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="es_ES";
UPDATE translations SET `value`="Graphenübersicht über Check-ins" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="de";
UPDATE translations SET `value`="Check-in par jour et horaire" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="fr";
UPDATE translations SET `value`="Check-in per orario e giorno" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="it";
UPDATE translations SET `value`="Check-ins per tijdsblok en dag" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="nl";
UPDATE translations SET `value`="Check-ins por dia e hora" WHERE `key`="gym_partner_web.partner_data.checkins_heatmap" and `locale`="pt_PT";
UPDATE translations SET `value`="Total de alunos por mês" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="pt_BR";
UPDATE translations SET `value`="Total of users per month" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="en";
UPDATE translations SET `value`="Total users per month" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="en_US";
UPDATE translations SET `value`="Monthly users" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="en_GB";
UPDATE translations SET `value`="Monthly users" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="en_IE";
UPDATE translations SET `value`="Usuarios totales por mes" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="es";
UPDATE translations SET `value`="Usuarios totales por mes" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="es_AR";
UPDATE translations SET `value`="Usuarios totales por mes" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="es_CL";
UPDATE translations SET `value`="Usuarios totales por mes" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="es_MX";
UPDATE translations SET `value`="Usuarios totales por mes" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="es_ES";
UPDATE translations SET `value`="
Anzahl der Nutzer pro Monat" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="de";
UPDATE translations SET `value`="Total d'utilisateurs par mois" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="fr";
UPDATE translations SET `value`="Totale utenti per mese" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="it";
UPDATE translations SET `value`="Totaal aantal gebruikers per maand" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="nl";
UPDATE translations SET `value`="Utilizadores totais por mês" WHERE `key`="gym_partner_web.partner_data.users_per_month" and `locale`="pt_PT";
